# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "xubuntu1804"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Update to latest
    printf "=== STEP: update to latest"
    apt-get update
    apt-get dist-upgrade -y

    # Add virtualbox guest utils
    printf "=== STEP: add virtualbox guest utils"
    apt-get install -y virtualbox-guest-utils

    # Install XFCE desktop environment
    printf "=== STEP: install XFCE desktop environment"
    apt-get install -y xubuntu-desktop

    #### CLEANUP (taken from https://gist.github.com/carlessanagustin/2fb92e88f2068300a2ed)
    ## for vagrant related tasks, uncomment vagrant comments

    # vagrant: Unmount project
    # printf "=== STEP: vagrant: Unmount project"
    # umount /vagrant

    # Remove APT cache
    printf "=== STEP: Remove APT cache"
    apt-get clean -y
    apt-get autoclean -y

    # Zero free space to aid VM compression
    printf "=== STEP: Zero free space to aid VM compression"
    dd if=/dev/zero of=/EMPTY bs=1M
    rm -f /EMPTY

    # Remove APT files
    printf "=== STEP: Remove APT files"
    find /var/lib/apt -type f | xargs rm -f

    # FIXME Remove documentation files
    # printf "=== STEP: Remove documentation files"
    # find /var/lib/doc -type f | xargs rm -f

    # vagrant: Remove Virtualbox specific files
    #printf "=== STEP: vagrant: Remove Virtualbox specific files"
    #rm -rf /usr/src/vboxguest* /usr/src/virtualbox-ose-guest*

    # Remove Linux headers
    printf "=== STEP: Remove Linux headers"
    rm -rf /usr/src/linux-headers*

    # FIXME Remove Unused locales (edit for your needs, this keeps only en*)
    # printf "=== STEP: Remove Unused locales"
    # find /usr/share/locale/{aa,ab,ace,ach,af,ak,am,an,ar,ary,as,ast,ay,az,ba,bar,be,be@latin,bem,bg,bi,bn,bn_IN,bo,br,brx,bs,byn,ca,ca@valencia,ce,ch,chr,ckb,cmn,co,crh,cs,csb,cv,cy,da,de,de_CH,de_DE,dv,dz,ee,el,eo,es,es_AR,es_CL,es_CO,es_MX,es_VE,et,eu,fa,fa_AF,fa_IR,ff,fi,fil,fo,fr,fr_CA,fr_FR,frp,fur,fy,ga,gd,gez,gl,gn,gu,gv,ha,haw,he,hi,hr,ht,hu,hy,ia,id,ig,io,is,it,iu,ja,jam,jv,ka,kab,ki,kk,kl,km,kn,ko,kok,ks,ku,ku_IQ,kv,kw,ky,la,lb,lg,li,ln,lo,locale.alias,lt,lv,mai,mg,mhr,mi,mk,ml,mn,mo,mr,ms,ms_MY,mt,my,my_MM,na,nah,nan,nb,nb_NO,nds,ne,nl,nn,nso,nv,oc,om,or,os,pa,pam,pap,pi,pl,pms,ps,pt,pt_BR,pt_PT,qu,rm,ro,ru,rw,sa,sc,sco,sd,se,shn,si,sk,sl,sn,so,son,sq,sr,sr@ije,sr@latin,sr@Latn,st,sv,sw,szl,ta,ta_LK,te,tg,th,ti,tig,tk,tl,tl_PH,tr,trv,tt,tt@iqtelif,ug,uk,ur,ur_PK,uz,uz@cyrillic,uz@Latn,ve,vec,vi,wa,wae,wal,wo,xh,yi,yo,zh_CN,zh_HK,zh_TW,zu} -type d -delete

    # Remove bash history
    printf "=== STEP: Remove bash history"
    unset HISTFILE
    rm -f /root/.bash_history

    # vagrant: Remove bash history
    # printf "=== STEP: vagrant: Remove bash history"
    # rm -f /home/vagrant/.bash_history

    # Cleanup log files
    printf "=== STEP: Cleanup log files"
    find /var/log -type f | while read f; do echo -ne '' > $f; done;

    # Whiteout root
    printf "=== STEP: Whiteout root"
    count=`df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}'`;
    count=$((count -= 1))
    dd if=/dev/zero of=/tmp/whitespace bs=1024 count=$count;
    rm /tmp/whitespace;

    # Whiteout /boot
    printf "=== STEP: Whiteout /boot"
    count=`df --sync -kP /boot | tail -n1 | awk -F ' ' '{print $4}'`;
    count=$((count -= 1))
    dd if=/dev/zero of=/boot/whitespace bs=1024 count=$count;
    rm /boot/whitespace;

    # Whiteout swap
    printf "=== STEP: Whiteout swap"
    swappart=`cat /proc/swaps | tail -n1 | awk -F ' ' '{print $1}'`
    swapoff $swappart;
    dd if=/dev/zero of=$swappart;
    mkswap $swappart;
    swapon $swappart;

    # Shutdown
    printf "=== STEP: Shutdown"
    shutdown now
  SHELL
end
